add_library(fluffos_compile_service STATIC
        "compile_service.cc"
        "compile_service.h"
        "compile_service_client.h"
        "compile_service_protocol.h"
        "runtime_compile_request.cc"
        "runtime_compile_request.h"
        "runtime_dev_test_request.cc"
        "runtime_dev_test_request.h"
        )
