string url_decode(string);
string url_encode(string);
mapping http_decode_query(string);
mapping http_decode_form(string);
string http_build_response(int, mapping, string);
mixed http_parser_create();
mapping http_parser_feed(mixed, string);
void http_parser_close(mixed);
mixed http_response_parser_create();
mapping http_response_parser_feed(mixed, string);
void http_response_parser_close(mixed);
